### PR TITLE
Add: EFKU,EFOU,EFRO,EFTP,EFTU

### PR DESCRIPTION
**Pull request by ottotuhkunen**
@Blt950 todo

### CODE REVIEW

**Comment by blt950** [comment]
Reminder to myself to look into this @blt950

**Comment by blt950** [comment]
@ottotuhkunen Looks good and works here.
Two things:

- Could you remove the .DS_STORE file that is committed
- Are FINxx stands a real stand or just some slip-up?

**Comment by ottotuhkunen** [comment]
> @ottotuhkunen Looks good and works here. Two things:
> 
> * Could you remove the .DS_STORE file that is committed
> * Are FINxx stands a real stand or just some slip-up?

@blt950 Sorry, DS file is now removed in the latest commit, I also added max wingspan values for stands at EFOU. FIHxx stands are the bases for the medical helicopters. Those are now days quite popular with the new EC145 MSFS addon.

**Comment by blt950** [comment]
Great :) This will be live in a few.

**Pull request merged**
