### PR TITLE
Reintroduce ENGM stand 47

### PR DESCRIPTION
**Pull request by Atriusftw**
With reference to https://github.com/Vatsim-Scandinavia/ENOR-Sectorfile/pull/401

To be updated when the new sector file is published.

### CODE REVIEW

**Comment by blt950** [comment]
Verified to work. Ping me when it's ready to be merged (as it's draft PR atm)

**Comment by Atriusftw** [comment]
This can be merged now, @blt950.

**Comment by blt950** [comment]
Will be available in next version of stands when we fix the all-stands-look-available-bug :D

**Comment by blt950** [comment]
@Atriusftw It's live now

**Pull request merged**
