### PR TITLE
Corrected ESSA changes

### PR DESCRIPTION
**Pull request by maxlk96**

### CODE REVIEW

**Comment by blt950** [comment]
Not sure if this quite correct "fix"? @maxlk96 
image

**Comment by blt950** [comment]
By converting AIP coordinates https://webtools.kusternet.ch/geo/coordinatesconverter with this seems more correct tbh
image

Can you please verify all your ESSA fixes in this and previous PR (https://github.com/Vatsim-Scandinavia/stands/pull/14) that they've correct coordinates please?

**Comment by maxlk96** [comment]
Thanks for correcting APN M, I added all the coordinates but somehow they got lost, no idea how...

Please confirm the following was done correctly (I tried my best...):
- Removal of additional S-stands, S1L etc.
- R10B repositioned

**Comment by blt950** [comment]
Seems good now. I'll merge this, please create a new PR if you still find errors.

**Pull request merged**
